# Generated by Django 4.0.1 on 2024-07-24 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order_orderproduct_order_products_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='product', through='core.OrderProduct', to='core.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.category'),
        ),
    ]
